###
### See characters
GET http://localhost:3000/charsTest

###
### Add character
POST http://localhost:3000/charsTest
Content-Type: application/json

{
    "name": "Jake Park",
    "icon": "https://raw.githubusercontent.com/dearvoodoo/dbd/master/Survivors/Portrait/JP.png",
    "category": "Survivor"
}

###
### See perks
GET http://localhost:3000/perksTest

###
### Add perk
### "<span class='perk-tier-3'>90</span>/<span class='perk-tier-2'>75</span>/<span class='perk-tier-1'>60</span>",

POST http://localhost:3000/perksTest
Content-Type: application/json

{
    "title": "Saboteur",
    "description": "Unlocks potential in one's Aura-reading ability. <ul><li> See Hook Auras in a radius of 56 metres from the pick-up spot if a Survivor is being carried.</li> <li>Unlocks the ability to sabotage Hooks without a Toolbox.</li> <li>Sabotaging a Hook without a Toolbox takes 2.5 seconds.</li> <li> The Sabotage action has a cool-down of <span class='perk-tier-3'>90</span>/<span class='perk-tier-2'>75</span>/<span class='perk-tier-1'>60</span> seconds.</li>",
    "icon": "https://raw.githubusercontent.com/mirceachirita/dbdbuilds/master/static/perks/saboteur.png",
    "category": "Survivor",
    "character": "5fb862615940e32aacd98833"
}

### 
### Delete perk

DELETE http://localhost:3000/perksTest/5fb8630f5940e32aacd98834