###
### See characters
GET http://localhost:3000/charsTest

###
### Add character
POST http://localhost:3000/charsTest
Content-Type: application/json

{
    "name": "Jake Park",
    "icon": "https://raw.githubusercontent.com/dearvoodoo/dbd/master/Survivors/Portrait/JP.png",
    "category": "Survivor"
}

###
### See perks
GET http://localhost:3000/perksTest

###
### Add perk
### "<span class='perk-tier-3'>90</span>/<span class='perk-tier-2'>75</span>/<span class='perk-tier-1'>60</span>",

POST http://localhost:3000/perksTest
Content-Type: application/json

{
    "title": "Empathy",
    "description": "Unlocks potential in one's Aura-reading ability.<br> Dying or Injured Allies' Auras are revealed to you when within <span class='perk-tier-3'>64</span>/<span class='perk-tier-2'>96</span>/<span class='perk-tier-3'>128</span> metres of range.<br> Empathy does not reveal Auras of Allies when they are in the Killer's direct contact.",
    "icon": "icon-perk-empathy",
    "category": "Survivor",
    "character": "5fb862615940e32aacd98833"
}

### 
### Delete perk

DELETE http://localhost:3000/perksTest/5fb9b6a2213ccb51e81f7ad4